apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-db-pv
  namespace: default
  labels:
    app: postgres-sql
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/c/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
