apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-claim
  namespace: postgres-with-pv
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
