apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-no-pv
  labels:
    app: postgres
data:
  POSTGRES_DB: admin_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres-no-pv
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      namespace: postgres-no-pv
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-no-pv
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
