{
 "title": "Pod Resource Usage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "The pod filter", "query": "app.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory(Mi) - Working Set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pod\"} / (1024*1024)) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\"$pod\",resource=\"memory\"}) by (pod) / (1024*1024)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$pod\",resource=\"memory\"}) by (pod) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory(Mi) - RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max(container_memory_rss{pod=~\"$pod\"} / (1024*1024)) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Play",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage COPY (PLAY)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[5m])) by (pod)\n",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"$pod\",resource=\"cpu\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"$pod\",resource=\"cpu\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=~\"$pod\"}[5m])) / ignoring(id) sum(increase(container_cpu_cfs_periods_total{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}