apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-sql
  name: postgresql-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30543
  selector:
    app: postgres-sql
  type: NodePort
status:
  loadBalancer: {}
